### ISSUE TITLE
[FEAT] 사용자 인증, 인가

### ISSUE THREAD

**Issue by Jin409** [hufscheer/spectator-server#145]
- [x] 관련 에러 핸들링 -> 500 뜨지 않도록
   - [x] 만료된 토큰 핸들링 
- [x] 테스트 코드 작성
- [ ] prod 환경 yaml 에 secret 추가

**Comment by Jin409** [comment]
auth 패키지 위치에 대한 고민

1. command (x)
DB 에 영향이나 변화를 주는 것이 아니기 때문에
2. query (-)
확신은 없으나 현존하는 구조 상으로는 가장 적절하지 않을까 생각했음
3. common (x)
common 에 위치하게 되면 기존에 정리해뒀던 의존성 흐름의 방향이 깨진다고 생각했음. command 와 query 모두에서 common 을 의존하고 있는데, auth 를 common 에 위치시켜버리게 되면 common 이 결국 Member 도메인이 위치한 command 를 참조하게 되기 떄문

**Comment by Jin409** [comment]
Member 에 getter 를 둬도 될까?
이유 : JwtTokenProvider 에서 Member 에 대한 정보가 필요 (email, password)

**Comment by Jin409** [comment]
쿠키에 대한 정보를 어디에 저장하는 것이 옳을까?

**Comment by Jin409** [comment]
authority 관련 논의가 필요하지 않을까?

**Comment by fingersdanny** [comment]
> Member 에 getter 를 둬도 될까? 이유 : JwtTokenProvider 에서 Member 에 대한 정보가 필요 (email, password)

불러올 수 있는 다른 방법이 없다면 붙여야하지 않을까? 모든 정보에 다 ``@Getter``를 다는게 좀 그렇다면 그 두 필드에만 열어놓아도 될거 같아

**Comment by Jin409** [comment]
SecurityConfig 를 common 에 두지 않은 이유

auth 패키지의 MemberDetails 와 AuthService 는 command 의 MemberRepository 를 의존 (auth >> command 로 의존성 방향이 흐름)
command 패키지에서는 EntityUtils 등을 의존하기 위해 common 을 의존 (command >> common 으로 의존성 방향이 흐름)
여기에서 SecurityConfig 를 common 에 두게 된다면 common 이 auth 패키지의 JwtProvider 를 의존하므로 auth >> common 으로 의존성 방향이 흐르게 됨

즉, SecurityConfig 를 common 에 두게 되면 `auth >> command >> common >> auth` 로 이어지게 됨

**Comment by Jin409** [comment]
MemberDetails 를 어떤 패키지에 넣어야 할까?

**Comment by fingersdanny** [comment]
> 쿠키에 대한 정보를 어디에 저장하는 것이 옳을까? 만료 기한, 이름 등 -> 지금은 컨트롤러에 있음.. 흠....

컨트롤러가 아닌 다른 곳에 두어야 한다면 ``HandlerInterceptor``같은걸 구현하는 방법도 있을 듯?? 해당 부분에서 응답에 쿠키만 추가해줄 수도 있을거 같아
